// <auto-generated />
using System;
using Listenarr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listenarr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    partial class ListenArrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Listenarr.Domain.ActivityHistory.DownloadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AudiobookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AudiobookId");

                    b.HasIndex("DownloadId");

                    b.HasIndex("EventDate");

                    b.HasIndex("DownloadId", "EventType");

                    b.ToTable("DownloadHistories", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.ActivityHistory.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudiobookExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudiobookTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadClientId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadId")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudiobookExternalId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DownloadClientId");

                    b.HasIndex("DownloadId");

                    b.HasIndex("EventType");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("Outcome");

                    b.HasIndex("Timestamp");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Listenarr.Domain.ActivityHistory.ProcessExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stderr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stdout")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessExecutionLogs");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.Audiobook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Abridged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorAsins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authors")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Explicit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSearchTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narrators")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSearchTime");

                    b.HasIndex("Monitored");

                    b.HasIndex("QualityProfileId");

                    b.ToTable("Audiobooks");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookDeletionIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudiobookId")
                        .IsUnique()
                        .HasFilter("\"State\" <> 'Completed'");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("AudiobookId", "State");

                    b.ToTable("AudiobookDeletionIntents", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookExternalIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueRaw")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudiobookId");

                    b.HasIndex("Type", "ValueNormalized");

                    b.HasIndex("AudiobookId", "Type", "IsPrimary");

                    b.HasIndex("Type", "ValueNormalized", "Region");

                    b.ToTable("AudiobookExternalIdentifiers", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathCaseSensitivity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("PathCaseSensitivityMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Auto");

                    b.Property<string>("PathIdentityBoundary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityLookupKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unavailable");

                    b.Property<int>("PathIdentityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("PathOwnershipKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSyntax")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PhysicalIdentityObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysicalIdentityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("PhysicalObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudiobookId");

                    b.HasIndex("PathIdentityLookupKey");

                    b.HasIndex("PathOwnershipKey")
                        .IsUnique()
                        .HasFilter("\"PathOwnershipKey\" IS NOT NULL");

                    b.ToTable("AudiobookFiles");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookSeriesMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesAsin")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AudiobookId");

                    b.HasIndex("AudiobookId", "IsPrimary");

                    b.HasIndex("AudiobookId", "SortOrder");

                    b.ToTable("AudiobookSeriesMemberships", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AuthorCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorAsin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogBooks")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SimilarAuthors")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAsin", "Region");

                    b.HasIndex("AuthorNameNormalized", "Region")
                        .IsUnique();

                    b.ToTable("AuthorCacheEntries");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.LibraryDirectoryOwnership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreationOperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationWorkflow")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryObjectIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryObjectIdentityUnavailableReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DirectoryObjectIdentityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagedRootFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathCaseSensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathCaseSensitivityMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityBoundary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityLookupKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathOwnershipKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSyntax")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagedRootFolderId");

                    b.HasIndex("OwnershipToken")
                        .IsUnique();

                    b.HasIndex("PathIdentityLookupKey");

                    b.HasIndex("PathOwnershipKey")
                        .IsUnique()
                        .HasFilter("\"PathOwnershipKey\" IS NOT NULL");

                    b.HasIndex("CreationOperationId", "State");

                    b.ToTable("LibraryDirectoryOwnerships", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.LibraryDirectoryOwnershipPathMigration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnershipId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RelocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCanonicalPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCaseSensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCaseSensitivityMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentityBoundary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentityLookupKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOwnershipKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePathSyntax")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCanonicalPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCaseSensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCaseSensitivityMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetIdentityBoundary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetIdentityLookupKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetOwnershipKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPathSyntax")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelocationId");

                    b.HasIndex("TargetOwnershipKey")
                        .IsUnique();

                    b.HasIndex("OwnershipId", "RelocationId")
                        .IsUnique();

                    b.ToTable("LibraryDirectoryOwnershipPathMigrations", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MonitoredAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorAsin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastCheckedAt");

                    b.HasIndex("AuthorNameNormalized", "Region", "Language")
                        .IsUnique();

                    b.ToTable("MonitoredAuthors");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MonitoredSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesAsin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastCheckedAt");

                    b.HasIndex("SeriesNameNormalized", "Region", "Language")
                        .IsUnique();

                    b.ToTable("MonitoredSeries");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveDeduplicationKey")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteEmptySource")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionProtocolVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("FailureKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<int>("IdentityKeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<Guid?>("RelocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCaseSensitivity")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCaseSensitivityMode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCleanupBoundary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDirectoryCleanupState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SourceDirectoryObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentityBoundary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePathSyntax")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCaseSensitivity")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCaseSensitivityMode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDirectoryObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetIdentityBoundary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPathSyntax")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDeduplicationKey")
                        .IsUnique()
                        .HasFilter("\"ActiveDeduplicationKey\" IS NOT NULL");

                    b.HasIndex("RelocationId");

                    b.HasIndex("AudiobookId", "Status");

                    b.HasIndex("Status", "NextAttemptAt", "LeaseExpiresAt");

                    b.ToTable("MoveJobs");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJobCreatedDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MoveJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MoveJobId", "Path")
                        .IsUnique();

                    b.ToTable("MoveJobCreatedDirectories", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJobEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CleanupProtectionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("CleanupState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MoveJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePhysicalObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPhysicalObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MoveJobId", "RelativePath")
                        .IsUnique();

                    b.ToTable("MoveJobEntries", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveScanHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MoveJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MoveJobId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt", "LeaseExpiresAt");

                    b.ToTable("MoveScanHandoffs", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.QualityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomGroupNames")
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomGroupNames");

                    b.Property<string>("CutoffQuality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MustContain")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MustContain");

                    b.Property<string>("MustNotContain")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MustNotContain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferNewerReleases")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredFormats")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PreferredFormats");

                    b.Property<string>("PreferredLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PreferredLanguages");

                    b.PrimitiveCollection<string>("PreferredWords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualities")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Qualities");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QualityProfiles");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseSensitivityMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Auto");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DirectoryObjectIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryObjectIdentityUnavailableReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DirectoryObjectIdentityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unavailable");

                    b.Property<string>("ResolvedCaseSensitivity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("IX_RootFolders_SingleDefault")
                        .HasFilter("\"IsDefault\" = 1");

                    b.HasIndex("Name");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("PathIdentityKey")
                        .IsUnique()
                        .HasFilter("\"PathIdentityKey\" IS NOT NULL");

                    b.ToTable("RootFolders", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveRootFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedJobs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteEmptySource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DesiredIsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesiredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RootFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceCaseSensitivityMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Auto");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCaseSensitivityMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDirectoryObjectIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDirectoryObjectIdentityUnavailableReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetDirectoryObjectIdentityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetIdentityEnrollmentState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Authorized");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRootFolderId")
                        .IsUnique()
                        .HasFilter("\"ActiveRootFolderId\" IS NOT NULL");

                    b.HasIndex("RootFolderId");

                    b.ToTable("RootFolderRelocations", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocationCreatedDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryObjectIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DirectoryObjectIdentityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnershipToken")
                        .IsUnique();

                    b.HasIndex("RelocationId", "CanonicalPath")
                        .IsUnique();

                    b.ToTable("RootFolderRelocationCreatedDirectories", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocationSkippedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelocationId", "AudiobookId")
                        .IsUnique();

                    b.ToTable("RootFolderRelocationSkippedItems", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.SeriesCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogBooks")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesAsin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesAsin", "Region");

                    b.HasIndex("SeriesNameNormalized", "Region")
                        .IsUnique();

                    b.ToTable("SeriesCacheEntries");
                });

            modelBuilder.Entity("Listenarr.Domain.Configuration.ApiConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HeadersJson");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ParametersJson");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RateLimitPerMinute")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiConfigurations");
                });

            modelBuilder.Entity("Listenarr.Domain.Configuration.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedFileExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudnexusApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedFileAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultSearchLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSearchRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordBotAvatar")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DiscordBotEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordBotToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordBotUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordCommandGroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordCommandSubcommandName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordGuildId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCompletionStabilitySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAmazonSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAudibleSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCoverArtDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableMetadataProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableOpenLibrarySearch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledNotificationTriggers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExtractArchives")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FailedDownloadAutoSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FailedDownloadHandlingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileNamingPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderNamingPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportBlacklistExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingSourceMaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingSourceRetryInitialDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MultiFileNamingPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProwlarrApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProwlarrPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProwlarrTagFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProwlarrUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowCompletedExternalDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedScanConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Webhooks")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("Listenarr.Domain.Downloads.CompatibilityFilePublicationJournal", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectiveAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompanionFile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedAction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceDisposition")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.HasIndex("AudiobookId");

                    b.HasIndex("State");

                    b.ToTable("CompatibilityFilePublicationJournals", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Downloads.Download", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveAudiobookDeduplicationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportAttempts")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ImportBlockMessages")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBlockReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveAudiobookDeduplicationKey")
                        .IsUnique()
                        .HasFilter("\"ActiveAudiobookDeduplicationKey\" IS NOT NULL");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("DownloadClientId");

                    b.HasIndex("Status");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("Listenarr.Domain.Downloads.DownloadClientConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoveCompletedDownloads")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SettingsJson");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSSL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadClientConfigurations");
                });

            modelBuilder.Entity("Listenarr.Domain.Downloads.DownloadProcessingJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveDeduplicationKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("JobData");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ProcessingLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDeduplicationKey")
                        .IsUnique()
                        .HasFilter("\"ActiveDeduplicationKey\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("DownloadId", "Status");

                    b.ToTable("DownloadProcessingJobs");
                });

            modelBuilder.Entity("Listenarr.Domain.Downloads.FileMutationJournal", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudiobookFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationParentDirectoryObjectIdentity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<long>("SourceLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceParentDirectoryObjectIdentity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePhysicalObjectIdentity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPhysicalObjectIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.HasIndex("State");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FileMutationJournals", (string)null);
                });

            modelBuilder.Entity("Listenarr.Domain.Downloads.RemotePathMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RemotePathMappings");
                });

            modelBuilder.Entity("Listenarr.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Listenarr.Domain.Identity.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Username");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Listenarr.Domain.Search.Indexer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimeCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAnimeStandardSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAutomaticSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableInteractiveSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestError")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastTestSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Retention")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Indexers");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.Audiobook", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.QualityProfile", "QualityProfile")
                        .WithMany()
                        .HasForeignKey("QualityProfileId");

                    b.Navigation("QualityProfile");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookExternalIdentifier", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.Audiobook", null)
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookFile", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.Audiobook", "Audiobook")
                        .WithMany("Files")
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audiobook");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookSeriesMembership", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.Audiobook", "Audiobook")
                        .WithMany("SeriesMemberships")
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audiobook");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.LibraryDirectoryOwnership", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.RootFolder", null)
                        .WithMany()
                        .HasForeignKey("ManagedRootFolderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.LibraryDirectoryOwnershipPathMigration", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.LibraryDirectoryOwnership", "Ownership")
                        .WithMany("PathMigrations")
                        .HasForeignKey("OwnershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Listenarr.Domain.Audiobooks.RootFolderRelocation", "Relocation")
                        .WithMany("OwnershipPathMigrations")
                        .HasForeignKey("RelocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ownership");

                    b.Navigation("Relocation");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJob", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.RootFolderRelocation", "Relocation")
                        .WithMany("MoveJobs")
                        .HasForeignKey("RelocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Relocation");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJobCreatedDirectory", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.MoveJob", "MoveJob")
                        .WithMany("CreatedDirectories")
                        .HasForeignKey("MoveJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoveJob");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJobEntry", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.MoveJob", "MoveJob")
                        .WithMany("Entries")
                        .HasForeignKey("MoveJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoveJob");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveScanHandoff", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.MoveJob", "MoveJob")
                        .WithOne("ScanHandoff")
                        .HasForeignKey("Listenarr.Domain.Audiobooks.MoveScanHandoff", "MoveJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoveJob");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocation", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.RootFolder", "RootFolder")
                        .WithMany("Relocations")
                        .HasForeignKey("RootFolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RootFolder");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocationCreatedDirectory", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.RootFolderRelocation", "Relocation")
                        .WithMany("CreatedDirectories")
                        .HasForeignKey("RelocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Relocation");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocationSkippedItem", b =>
                {
                    b.HasOne("Listenarr.Domain.Audiobooks.RootFolderRelocation", "Relocation")
                        .WithMany("SkippedItems")
                        .HasForeignKey("RelocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relocation");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.Audiobook", b =>
                {
                    b.Navigation("ExternalIdentifiers");

                    b.Navigation("Files");

                    b.Navigation("SeriesMemberships");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.LibraryDirectoryOwnership", b =>
                {
                    b.Navigation("PathMigrations");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.MoveJob", b =>
                {
                    b.Navigation("CreatedDirectories");

                    b.Navigation("Entries");

                    b.Navigation("ScanHandoff");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolder", b =>
                {
                    b.Navigation("Relocations");
                });

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolderRelocation", b =>
                {
                    b.Navigation("CreatedDirectories");

                    b.Navigation("MoveJobs");

                    b.Navigation("OwnershipPathMigrations");

                    b.Navigation("SkippedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
